config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en/ do
    devise_for :users
    root "static_pages#home"
    get "courses/show"
    get "static_pages/subject"
    get "static_pages/in_subject"
    get "static_pages/report"
    get "static_pages/login"
    get "static_pages/profile"
    get "static_pages/edit_profile"
    post "add_user", to: "user_add_by_trainers#create"
    post "live_search", to: "live_search_forms#create"

    resources :user_courses
    resources :subjects
    resources :user_subjects
    resources :course_subjects
    resources :courses
    resources :users do
      collection {post :import}
    end
    resources :admin, controller: "users", role: "Admin"
    resources :trainer, controller: "users", role: "Trainer"
    resources :trainee, controller: "users", role: "Trainee"
    resources :user_reports
    resources :view_details
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :login

  def home
    @user = User.new
    @user_course = UserCourse.new
    @course_subject = CourseSubject.new
    @options = Subject.all
  end

  def subject; end

  def in_subject; end

  def report; end

  def profile; end

  def edit_profile; end
  private

  def login
    return if user_signed_in?
    flash[:danger] = t "please_login"
    redirect_to new_user_session_path
  end
end

app/views/static_pages/home.html.erb
<div class="row">
  <div class="col-md-3 col-md-offset-1">
    <%= link_to  "New course", new_course_path, class: "btn btn-primary" %>
  </div>
</div>
<div>
  <h4><%= t ".import_csv" %></h4>
  <%= form_tag import_users_path, multipart: true do %>
    <%= file_field_tag :file %>
    <br>
    <%= submit_tag t(".import"), class: "btn btn-success" %>
  <% end %>
</div>
<div>
  <h4><%= t ".add_user" %></h4>
  <button class="btn btn-primary" data-toggle="modal"
    data-target="#modal-window-add-user">
    <%= t ".add_user" %>
  </button>
  <%= render "users/new_modal" %>
<div>
  <%= link_to  t(".all_trainee"), users_path, class: "btn btn-primary"%>
</div>
</div>
<div>
  <h4><%= t ".create_user_course" %></h4>
  <button class="btn btn-primary" data-toggle="modal"
    data-target="#modal-window-create-user-course">
    <%= t ".create_user_course" %>
  </button>
  <%= render "user_courses/new_modal" %>
</div>
<div>
  <h4><%= t ".create_course_subject" %></h4>
  <button class="btn btn-primary" data-toggle="modal"
    data-target="#modal-window-create-course-subject">
    <%= t ".create_course_subject" %>
  </button>
  <%= render "course_subjects/new_modal" %>
</div>

app/views/static_pages/in_subject.html.erb
<div class="title">
  <h3 class="box-title name">Git Tutorial</h3>
  <div class="subject-status clearfix">
    <span class="status finished">Finished</span>
  </div>
</div>
<div class="row">
  <div class="col-md-9">
    <div class="slimScrollDiv">
      <div class="description">
        <div class="box-content">
          <div class="pull-left title">Resources</div>
          <div class="pull-right"><a href="#show-content" class="text" data-toggle="collapse">Show more</a></div>
          <div class="clearfix"></div>
        </div>
        <div id="show-content" class="collapse show-panel">
          <p>[Git]</p>
          <p><a href="http://git-scm.com/book" target="_blank">http://git-scm.com/book</a> - 4 chương đầu&nbsp;&nbsp;</p>
          <p><a href="http://backlogtool.com/git-guide/vn/intro/intro1_1.html" target="_blank">http://backlogtool.com/git-guide/vn/intro/intro1_1.html</a>&nbsp;</p>
          <p><a href="http://chris.beams.io/posts/git-commit/" target="_blank">http://chris.beams.io/posts/git-commit/</a>&nbsp;</p>
          <p>[Slide tham khảo]</p>
          <p><a href="https://docs.google.com/presentation/d/13UFE6PupQxlT_XAOx6AJJUXJCjOjkum8tOjj96dr37E/edit#slide=id.p3" target="_blank">https://docs.google.com/presentation/d/13UFE6PupQxlT_XAOx6AJJUXJCjOjkum8tOjj96dr37E/edit#slide=id.p3</a>&nbsp;</p>
          <p></p>
          <p>[Video]</p>
          <p><a href="https://www.youtube.com/watch?v=OBCnmcgx4CE" target="_blank">https://www.youtube.com/watch?v=OBCnmcgx4CE</a>&nbsp;</p>
          <p>Kết thúc học các em sẽ làm bài test GIT, tối đa có 3 lần test, kết quả tối thiểu để pass bài test là 25/30</p>
          <p>[Link test]</p>
          <p><a href="http://training.framgia.vn/" target="_blank">http://training.framgia.vn/</a>&nbsp;</p>
        </div>
      </div>
      <div class="clearfix"></div>
      <p></p>
      <div class="column-chart">
        <table>
        </table>
      </div>
      <div class="assignment-box">
        <div class="list-assignment">
          <h1 class="header-task"><!-- react-text: 172 -->Task Overview<span class="label label-danger label-header">10 tasks</span><!-- react-text: 174 --></h1>
          <div class="assignment-item clearfix">
            <div class="col-md-2 avatar-user">
              <a>
                <%= image_tag "user.png", class: "img-circle" %>
              </a>
            </div>
            <div class="col-md-10 info-detail">
              <div class="row title-assignment">
                <div class="div-status" title="In Progress">
                  <!-- react-text: 265 -->in_progress
                  <em class="status status-progress cursor"></em></div>
                <p class="name">Getting Started</p>
                <p class="content-assignment">Get an introduction to project git</p>
              </div>
              <div class="row">
                <div class="col-md-6 border-right info"><i class="fa fa-calendar"></i>
                  <!-- react-text: 272 -->Started at:

                  <!-- react-text: 273 -->04/07/2018 08:24 am

                </div>
                <div class="col-md-6 info"><i class="fa fa-calendar"></i>
                  <!-- react-text: 276 -->Finished at:

                  <!-- react-text: 277 -->

                </div>
              </div>
              <div class="">
                <p><a href="#show-meta-tasks-32723" class="text" data-toggle="collapse">Submission</a></p>
                <div id="show-meta-tasks-32723" class="collapse show-panel"></div>
              </div>
            </div>
          </div>
          <div class="assignment-item clearfix">
            <div class="col-md-2 avatar-user">
              <a>
                <%= image_tag "user.png", class: "img-circle" %>
              </a>
            </div>
            <div class="col-md-10 info-detail">
              <div class="row title-assignment">
                <div class="div-status" title="Init">
                  <!-- react-text: 289 -->init
                  <em class="status status-init cursor"></em></div>
                <p class="name">Git Basics</p>
                <p class="content-assignment">Get an introduction to project git</p>
              </div>
              <div class="row">
                <div class="col-md-6 border-right info"><i class="fa fa-calendar"></i>
                  <!-- react-text: 296 -->Started at:

                  <!-- react-text: 297 -->

                </div>
                <div class="col-md-6 info"><i class="fa fa-calendar"></i>
                  <!-- react-text: 300 -->Finished at:

                  <!-- react-text: 301 -->

                </div>
              </div>
              <div class="">
                <p><a href="#show-meta-tasks-32724" class="text" data-toggle="collapse">Submission</a></p>
                <div id="show-meta-tasks-32724" class="collapse show-panel"></div>
              </div>
            </div>
          </div>
          <div class="assignment-item clearfix">
            <div class="col-md-2 avatar-user">
              <a>
                <%= image_tag "user.png", class: "img-circle" %>
              </a>
            </div>
            <div class="col-md-10 info-detail">
              <div class="row title-assignment">
                <div class="div-status" title="Init">
                  <!-- react-text: 313 -->init
                  <em class="status status-init cursor"></em></div>
                <p class="name">Git Branching</p>
                <p class="content-assignment">Get an introduction to project git</p>
              </div>
              <div class="row">
                <div class="col-md-6 border-right info"><i class="fa fa-calendar"></i>
                  <!-- react-text: 320 -->Started at:

                  <!-- react-text: 321 -->

                </div>
                <div class="col-md-6 info"><i class="fa fa-calendar"></i>
                  <!-- react-text: 324 -->Finished at:

                  <!-- react-text: 325 -->

                </div>
              </div>
              <div class="">
                <p><a href="#show-meta-tasks-32725" class="text" data-toggle="collapse">Submission</a></p>
                <div id="show-meta-tasks-32725" class="collapse show-panel"></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-3">
    <div class="slimScrollDiv">
      <div class="panel-right-info-trainee" style="overflow: hidden; width: auto; height: 132px;">
        <div class="member_user_course">
          <div class="info-panel clearfix">
            <div class="box-border box-top-custom">
              <div class="box-header with-border box-header-gray">
                <h3 class="label box-title">Members</h3><span class="badge label-primary">15</span></div>
              <div class="box-body">
                <div>
                  <div class="member-title">Trainers(0)
                  </div>
                  <ul class="user-list clearfix">
                    <ul class="user-list clearfix"></ul>
                  </ul>
                  <div class="member-title">Trainee(3)
                  </div>
                  <ul class="member-list clearfix">
                    <li class="member-item"><a href="#" class="cursor"><img class="img-circle" src="/assets/user.png" width="30" height="30"><span>Hoàng Tùng Lâm</span></a></li>
                    <li class="member-item"><a href="#" class="cursor"><img class="img-circle" src="/assets/user.png" width="30" height="30"><span>Nguyễn Văn Dương</span></a></li>
                    <li class="member-item"><a href="#" class="cursor"><img class="img-circle" src="/assets/user.png" width="30" height="30"><span>Đỗ Khắc Hưng</span></a></li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/profile.html.erb
<div class="">
  <div class="page-title">
    <div class="title_left">
      <h3>User Profile</h3>
    </div>
  </div>
  <div class="clearfix"></div>
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2>User Report <small>Activity report</small></h2>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <div class="col-md-3 col-sm-3 col-xs-12 profile_left">
            <div class="profile_img">
              <div id="crop-avatar">
                <!-- Current avatar -->
                <div class="avatar-view">
                  <%= image_tag "img.jpg" %>
                </div>
                <button class="btn btn-success">Upfile</button>
                <!-- Loading state -->
                <div class="loading" aria-label="Loading" role="img" tabindex="-1"></div>
              </div>
              <!-- end of image cropping -->
            </div>
            <h3>Samuel Doe</h3>
            <ul class="list-unstyled user_data">
              <li><i class="fa fa-map-marker user-profile-icon"></i> San Francisco, California, USA
              </li>
              <li>
                <i class="fa fa-briefcase user-profile-icon"></i> Software Engineer
              </li>
              <li class="m-top-xs">
                <i class="fa fa-external-link user-profile-icon"></i>
                <a href="http://www.kimlabs.com/profile/" target="_blank">www.kimlabs.com</a>
              </li>
            </ul>
            <a class="btn btn-success"><i class="fa fa-edit m-right-xs"></i>Edit Profile</a>
            <br />
            <!-- start skills -->
            <h4>Skills</h4>
            <ul class="list-unstyled user_data">
              <li>
                <p>Web Applications</p>
                <div class="progress progress_sm">
                  <div class="progress-bar bg-green" role="progressbar" data-transitiongoal="50"></div>
                </div>
              </li>
              <li>
                <p>Website Design</p>
                <div class="progress progress_sm">
                  <div class="progress-bar bg-green" role="progressbar" data-transitiongoal="70"></div>
                </div>
              </li>
              <li>
                <p>Automation & Testing</p>
                <div class="progress progress_sm">
                  <div class="progress-bar bg-green" role="progressbar" data-transitiongoal="30"></div>
                </div>
              </li>
              <li>
                <p>UI / UX</p>
                <div class="progress progress_sm">
                  <div class="progress-bar bg-green" role="progressbar" data-transitiongoal="50"></div>
                </div>
              </li>
            </ul>
            <!-- end of skills -->
          </div>
          <div class="col-md-9 col-sm-9 col-xs-12">
            <div class="" role="tabpanel" data-example-id="togglable-tabs">
              <ul id="myTab" class="nav nav-tabs bar_tabs" role="tablist">
                <li role="presentation" class="active"><a href="#tab_content1" id="home-tab" role="tab" data-toggle="tab" aria-expanded="true">Recent Activity</a>
                </li>
                <li role="presentation" class=""><a href="#tab_content2" role="tab" id="profile-tab" data-toggle="tab" aria-expanded="false">Projects Worked on</a>
                </li>
                <li role="presentation" class=""><a href="#tab_content3" role="tab" id="profile-tab2" data-toggle="tab" aria-expanded="false">Profile</a>
                </li>
                <li role="presentation" class=""><a href="#tab_content4" role="tab" id="profile-tab3" data-toggle="tab" aria-expanded="false">Training calendar</a>
                </li>
              </ul>
              <div id="myTabContent" class="tab-content">
                <div role="tabpanel" class="tab-pane fade active in" id="tab_content1" aria-labelledby="home-tab">
                  <!-- start recent activity -->
                  <ul class="messages">
                    <li>
                      <%= image_tag "img.jpg", class: "avatar" %>
                        <div class="message_date">
                          <h3 class="date text-info">24</h3>
                          <p class="month">May</p>
                        </div>
                        <div class="message_wrapper">
                          <h4 class="heading">Desmond Davison</h4>
                          <blockquote class="message">Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua butcher retro keffiyeh dreamcatcher synth.</blockquote>
                          <br />
                          <p class="url">
                            <span class="fs1 text-info" aria-hidden="true" data-icon=""></span>
                            <a href="#"><i class="fa fa-paperclip"></i> User Acceptance Test.doc </a>
                          </p>
                        </div>
                    </li>
                    <li>
                      <%= image_tag "img.jpg", class: "avatar" %>
                        <div class="message_date">
                          <h3 class="date text-error">21</h3>
                          <p class="month">May</p>
                        </div>
                        <div class="message_wrapper">
                          <h4 class="heading">Brian Michaels</h4>
                          <blockquote class="message">Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua butcher retro keffiyeh dreamcatcher synth.</blockquote>
                          <br />
                          <p class="url">
                            <span class="fs1" aria-hidden="true" data-icon=""></span>
                            <a href="#" data-original-title="">Download</a>
                          </p>
                        </div>
                    </li>
                  </ul>
                  <!-- end recent activity -->
                </div>
                <div role="tabpanel" class="tab-pane fade" id="tab_content2" aria-labelledby="profile-tab">
                  <!-- start user projects -->
                  <table class="data table table-striped no-margin">
                    <thead>
                      <tr>
                        <th>#</th>
                        <th>Project Name</th>
                        <th>Client Company</th>
                        <th class="hidden-phone">Hours Spent</th>
                        <th>Contribution</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td>1</td>
                        <td>New Company Takeover Review</td>
                        <td>Deveint Inc</td>
                        <td class="hidden-phone">18</td>
                        <td class="vertical-align-mid">
                          <div class="progress">
                            <div class="progress-bar progress-bar-success" data-transitiongoal="35"></div>
                          </div>
                        </td>
                      </tr>
                      <tr>
                        <td>2</td>
                        <td>New Partner Contracts Consultanci</td>
                        <td>Deveint Inc</td>
                        <td class="hidden-phone">13</td>
                        <td class="vertical-align-mid">
                          <div class="progress">
                            <div class="progress-bar progress-bar-danger" data-transitiongoal="15"></div>
                          </div>
                        </td>
                      </tr>
                      <tr>
                        <td>3</td>
                        <td>Partners and Inverstors report</td>
                        <td>Deveint Inc</td>
                        <td class="hidden-phone">30</td>
                        <td class="vertical-align-mid">
                          <div class="progress">
                            <div class="progress-bar progress-bar-success" data-transitiongoal="45"></div>
                          </div>
                        </td>
                      </tr>
                      <tr>
                        <td>4</td>
                        <td>New Company Takeover Review</td>
                        <td>Deveint Inc</td>
                        <td class="hidden-phone">28</td>
                        <td class="vertical-align-mid">
                          <div class="progress">
                            <div class="progress-bar progress-bar-success" data-transitiongoal="75"></div>
                          </div>
                        </td>
                      </tr>
                    </tbody>
                  </table>
                  <!-- end user projects -->
                </div>
                <div role="tabpanel" class="tab-pane fade profile-container clearfix" id="tab_content3" aria-labelledby="profile-tab">
                  <div class="col-md-6">
                    <table class="table table-user-information">
                      <tbody>
                        <tr>
                          <td>Name</td>
                          <td>Phạm Thị Linh</td>
                        </tr>
                        <tr>
                          <td>Email</td>
                          <td>cauvong9696@gmail.com</td>
                        </tr>
                        <tr>
                          <td>University</td>
                          <td>Posts and Telecommunications Institute of Technology</td>
                        </tr>
                        <tr>
                          <td>Working days / week</td>
                          <td>4</td>
                        </tr>
                        <tr>
                          <td>Status</td>
                          <td>In Progress</td>
                        </tr>
                        <tr>
                          <td>Graduation</td>
                          <td></td>
                        </tr>
                        <tr>
                          <td>Ready for project</td>
                          <td></td>
                        </tr>
                        <tr>
                          <td>Start training date</td>
                          <td>2018-07-03</td>
                        </tr>
                        <tr></tr>
                        <tr>
                          <td>Description</td>
                          <td></td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
                  <div class="col-md-6">
                    <table class="table table-user-information">
                      <tbody>
                        <tr>
                          <td>Organization</td>
                          <td>Laboratory</td>
                        </tr>
                        <tr>
                          <td>Program</td>
                          <td></td>
                        </tr>
                        <tr>
                          <td>Staff code</td>
                          <td></td>
                        </tr>
                        <tr>
                          <td>Language</td>
                          <td>Ruby</td>
                        </tr>
                        <tr>
                          <td>Type</td>
                          <td>Practice</td>
                        </tr>
                        <tr>
                          <td>Stage</td>
                          <td>In education</td>
                        </tr>
                        <tr>
                          <td>Contract date</td>
                          <td></td>
                        </tr>
                        <tr>
                          <td>Division</td>
                          <td>Human Development Division</td>
                        </tr>
                        <tr>
                          <td>Experience</td>
                          <td></td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
                </div>
                <div role="tabpanel" class="tab-pane fade" id="tab_content4" aria-labelledby="profile-tab">
                  abc
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/report.html.erb
<%= form_for :post do |form| %>
  <div class="field">
    <%= form.label :report %>
    <%= form.text_area :report, "data-provider": :summernote %>
    <%= form.submit "Submit", class: "btn btn-success" %>
  </div>
<% end %>