config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en/ do
    devise_for :users
    root "static_pages#home"
    get "courses/show"
    get "static_pages/subject"
    get "static_pages/in_subject"
    get "static_pages/report"
    get "static_pages/login"
    get "static_pages/profile"
    get "static_pages/edit_profile"
    post "add_user", to: "user_add_by_trainers#create"
    post "live_search", to: "live_search_forms#create"

    resources :user_courses
    resources :subjects
    resources :user_subjects
    resources :course_subjects
    resources :courses
    resources :users do
      collection {post :import}
    end
    resources :admin, controller: "users", role: "Admin"
    resources :trainer, controller: "users", role: "Trainer"
    resources :trainee, controller: "users", role: "Trainee"
    resources :user_reports
    resources :view_details
  end
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :user_subjects
  has_many :course_subjects

  validates :name, :detail, presence: true

  enum status: {active: 0, unactive: 1}
  enum category: {git: 0, ruby: 1, rails: 2}

  def get_category
    I18n.t("subject_type_#{self.category}")
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :find_subject, only: [:edit, :update]

  def index
    @subjects = Subject.all

    return if @subjects
    flash[:danger] = t "load_data_fail"
    redirect_to root_url
  end

  def new
    @subject = Subject.new
  end

  def create
    subject = Subject.new subject_params

    if subject.save
      flash[:success] = t "success"
      redirect_to subjects_path
    else
      flash[:danger] = t "no_success"
      render :new
    end
  end

  def edit; end

  def update
    if params[:subject][:name]
      update_subject
    else
      @subject.update status: params[:subject][:status].to_i
    end
  end

  private

  def find_subject
    @subject = Subject.find_by id: params[:id]

    return if @subject
    flash[:danger] = t "load_data_fail"
    redirect_to subjects_path
  end

  def subject_params
    params.require(:subject).permit :name, :detail, :category, :status
  end

  def update_subject
    if @subject.update_attributes subject_params
      flash[:success] = t "success"
      redirect_to subjects_url
    else
      flash[:success] = t "no_success"
      render :edit
    end
  end
end

app/views/subjects/edit.html.erb
<div class="row">
  <div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
      <div class="x_title">
        <h2><%= edit_subject %></h2>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
        <br />
        <%= form_for @subject, url: subject_path, method: :patch,
          class:"form-horizontal form-label-left" do |f| %>
          <div class="form-group row">
            <%= f.label :name, t("name"),
              class:"control-label col-md-3 col-sm-3 col-xs-12" %>
            <div class="col-md-6 col-sm-6 col-xs-12">
              <%= f.text_field :name, required:"required",
                class: "form-control col-md-7 col-xs-12" %>
            </div>
          </div>
          <div class="form-group row">
            <%= f.label :name, t("detail"),
              class:"control-label col-md-3 col-sm-3 col-xs-12" %>
            <div class="col-md-6 col-sm-6 col-xs-12">
              <%= f.text_area :detail, required:"required",
                class: "form-control col-md-7 col-xs-12" %>
            </div>
          </div>
          <div class="form-group row">
            <%= f.label :category, t("category"),
              class:"control-label col-md-3 col-sm-3 col-xs-12" %>
            <div class="col-md-9 col-sm-9 col-xs-12">
              <%= f.select :category, options_for_select(
                Subject.categories.keys.map {|key| [Settings.send(key), key]},
                selected: @subject.category), class: "select-custom" %>
            </div>
          </div>
          <div class="form-group row">
            <%= f.label :name, t("status"),
              class:"control-label col-md-3 col-sm-3 col-xs-12" %>
            <div class="col-md-6 col-sm-6 col-xs-12">
              <%= f.radio_button :status, "active" %>
              <%= f.label :active, Settings.active, class: "field-label"%>
              <br/>
              <%= f.radio_button :status, "unactive" %>
              <%= f.label :unactive, Settings.unactive, class: "field-label"%>
            </div>
          </div>
          <div class="clearfix"></div>
          <div class="ln_solid"></div>
          <div class="form-group">
            <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
              <%= link_to t("cancel"), subjects_path, class: "btn btn-primary" %>
              <%= link_to t("reset"), edit_subject_path(@subject),
                class: "btn btn-primary" %>
              <%= f.submit t("update"), class: "btn btn-success submit-button" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/subjects/index.html.erb
<div class="">
  <div class="page-title">
    <div class="title_left">
      <h3><%= t "current_subject" %></h3>
    </div>

    <div class="title_right">
    <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
      <div class="input-group">
      <input type="text" class="form-control" placeholder=<%= t "search" %>>
      <span class="input-group-btn">
        <button class="btn btn-default" type="button">
          <%= t "search_course" %>
        </button>
      </span>
      </div>
    </div>
    </div>
  </div>

  <div class="clearfix"></div>

  <div class="row">
    <div class="clearfix"></div>

    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_content">

        <div class="table-responsive">
          <table class="table table-striped jambo_table bulk_action">
            <thead>
              <tr class="headings">
                <th class="column-title">
                  <%= t "name" %>
                </th>
                <th class="column-title">
                  <%= t "detail" %>
                </th>
                <th class="column-title">
                  <%= t "category" %>
                </th>
                <th class="column-title">
                  <%= t "status" %>
                </th>
                <th class="column-title"><span class="nobr">
                  <%= t "view_subject" %>
                  </span>
                </th>
                <th class="column-title no-link last"><span class="nobr">
                  <%= t "edit_subject" %>
                  </span>
                </th>
              </tr>
            </thead>
            <tbody>
              <% @subjects.each do |subject| %>
                <%= form_for subject, url: subject_path(subject), method: :patch do |f| %>
                  <tr class="even pointer">
                    <td>
                      <%= hidden_field_tag "subject_id", subject.id %>
                      <%= subject.name %>
                    </td>
                    <td>
                      <%= subject.detail %>
                    </td>
                    <td>
                      <%= subject.get_category %>
                    </td>
                    <td>
                        <%= radio_button_tag :status, "0", subject.active?,
                          class: "update-subject", data: {id: subject.id} %>
                        <%= label_tag :category_0, "Active", class: "field-label" %>
                        <br>
                        <%= radio_button_tag :status, "1", subject.unactive?,
                          class: "update-subject", data: {id: subject.id} %>
                        <%= label_tag :category_1, "Unactive" ,class: "field-label" %>
                    </td>
                    <td>
                      <%= link_to t("view_subject"), user_subject_path(subject.id) %>
                    </td>
                    <td class="last">
                      <%= link_to t("edit_subject"), edit_subject_path(subject.id) %>
                    </td>
                  </tr>
                <% end %>
              <% end %>
            </tbody>
          </table>
          <%= link_to t("back"), root_url, class: "btn btn-primary col-md-1 col-sm-1 col-xs-3" %>
          <%= link_to t("create"), new_subject_path,
            class: "btn btn-success col-md-1 col-sm-1 col-xs-3" %>
        </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/subjects/new.html.erb
<div class="row">
  <div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
      <div class="x_title">
        <h2><%= t "create_subject" %></h2>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
        <br />
        <%= form_for :subject, url: subjects_path,
          class:"form-horizontal form-label-left" do |f| %>
          <div class="form-group">
            <%= f.label :name, t("name"),
              class:"control-label col-md-3 col-sm-3 col-xs-12" %>
            <div class="col-md-6 col-sm-6 col-xs-12">
              <%= f.text_field :name, required:"required",
                class: "form-control col-md-7 col-xs-12" %>
            </div>
          </div>
          <br/>
          <br/>
          <br/>
          <div class="form-group">
            <%= f.label :name, t("detail"),
              class:"control-label col-md-3 col-sm-3 col-xs-12" %>
            <div class="col-md-6 col-sm-6 col-xs-12">
              <%= f.text_area :detail, required:"required",
                class: "form-control col-md-7 col-xs-12" %>
            </div>
          </div>
          <br/>
          <br/>
          <br/>
          <br/>
          <div class="form-group">
            <%= f.label :category, t("category"),
              class:"control-label col-md-3 col-sm-3 col-xs-12" %>
            <div class="col-md-9 col-sm-9 col-xs-12">
              <%= f.select :category, options_for_select(
                [Settings.git, Settings.ruby, Settings.rails],
                selected: Settings.git), class: "select-custom" %>
            </div>
          </div>
          <br/>
          <br/>
          <div class="form-group">
            <%= f.label :name, t("status"),
              class:"control-label col-md-3 col-sm-3 col-xs-12" %>
            <div class="col-md-6 col-sm-6 col-xs-12">
              <%= f.radio_button :status, "active", checked: true %>
              <%= f.label :active, Settings.active, class: "field-label"%>
              <br/>
              <%= f.radio_button :status, "unactive" %>
              <%= f.label :unactive, Settings.unactive, class: "field-label"%>
            </div>
          </div>
          <div class="clearfix"></div>
          <div class="ln_solid"></div>
          <div class="form-group">
            <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
              <%= link_to t("cancel"), subjects_path, class: "btn btn-primary" %>
              <%= f.submit t("create"), class: "btn btn-success submit-button" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/subjects/show.html.erb
<div class="">
  <div class="page-title">
    <div class="title_left">
      <h3><%= t "current_subject" %></h3>
    </div>

    <div class="title_right">
    <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
      <div class="input-group">
      <input type="text" class="form-control" placeholder="Search for...">
      <span class="input-group-btn">
        <button class="btn btn-default" type="button">
          <%= t "search_course" %>
        </button>
      </span>
      </div>
    </div>
    </div>
  </div>

  <div class="clearfix"></div>

  <div class="row">
    <div class="clearfix"></div>

    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_content">

        <div class="table-responsive">
          <table class="table table-striped jambo_table bulk_action">
            <thead>
              <tr class="headings">
                <th>
                  <input type="checkbox" id="check-all" class="flat">
                </th>
                <th class="column-title">
                  <%= t "name" %>
                </th>
                <th class="column-title">
                  <%= t "detail" %>
                </th>
                <th class="column-title">
                  <%= t "category" %>
                </th>
                <th class="column-title">
                  <%= t "status" %>
                </th>
                <th class="column-title no-link last"><span class="nobr">
                  <%= t "action" %>
                </span>
                </th>
              </tr>
            </thead>
            <tbody>
              <% @subject.each do |subject| %>
                <tr class="even pointer">
                  <td class="a-center ">
                    <input type="checkbox" class="flat" name="table_records">
                  </td>
                  <td class=" ">
                    <%= hidden_field_tag "subject_id", subject.id %>
                    <%= subject.name %>
                  </td>
                  <td class=" ">
                    <%= subject.detail %>
                  </td>
                  <td class=" ">
                    <%= subject.get_category %>
                  </td>
                  <td class=" ">
                    <%= subject.get_status %>
                  </td>
                  <td class="last">
                    <%= link_to t(".view_subject"), "#" %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        </div>
      </div>
    </div>
  </div>
</div>