config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en/ do
    devise_for :users
    root "static_pages#home"
    get "courses/show"
    get "static_pages/subject"
    get "static_pages/in_subject"
    get "static_pages/report"
    get "static_pages/login"
    get "static_pages/profile"
    get "static_pages/edit_profile"
    post "add_user", to: "user_add_by_trainers#create"
    post "live_search", to: "live_search_forms#create"

    resources :user_courses
    resources :subjects
    resources :user_subjects
    resources :course_subjects
    resources :courses
    resources :users do
      collection {post :import}
    end
    resources :admin, controller: "users", role: "Admin"
    resources :trainer, controller: "users", role: "Trainer"
    resources :trainee, controller: "users", role: "Trainee"
    resources :user_reports
    resources :view_details
  end
end

app/models/user_subject.rb
class UserSubject < ApplicationRecord
  belongs_to :user
  belongs_to :subject
  belongs_to :user_course
  has_many :user_reports

  enum status: {active: 0, unactive: 1}
end

app/controllers/user_subjects_controller.rb
class UserSubjectsController < ApplicationController
  before_action :find_user_subject, only: [:edit, :update]

  def show
    @user_subjects = UserSubject.where subject_id: params[:id]
  end

  def edit; end

  def update
    if params[:user_subject][:progress]
      update_user_subject
    else
      @user_subject.update status: params[:user_subject][:status].to_i
    end
  end

  private

  def user_subject_params
    params.require(:user_subject)
          .permit :progress, :start_date, :end_date, :status
  end

  def update_user_subject
    if @user_subject.update_attributes user_subject_params
      flash[:success] = t "success"
      redirect_to user_subject_path @user_subject.subject_id
    else
      flash[:success] = t "no_success"
      render :edit
    end
  end

  def find_user_subject
    @user_subject = UserSubject.find_by id: params[:id]

    return if @user_subject
    flash[:danger] = t "load_data_fail"
    redirect_to user_subject_path @user_subject.subject_id
  end
end

app/views/user_subjects/edit.html.erb
<div class="row">
  <div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
      <div class="x_title">
        <h2><%= t "edit_subject" %></h2>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
        <br />
        <%= form_for @user_subject, url: user_subject_path, method: :patch,
          class:"form-horizontal form-label-left" do |f| %>
          <div class="form-group row">
            <%= f.label :progress, t("progress"),
              class:"control-label col-md-3 col-sm-3 col-xs-12" %>
            <div class="col-md-6 col-sm-6 col-xs-12">
              <%= f.text_field :progress, required:"required",
                class: "form-control col-md-7 col-xs-12" %>
            </div>
          </div>
          <div class="form-group row">
            <%= f.label :start_date, t("start_date"),
              class:"control-label col-md-3 col-sm-3 col-xs-12" %>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <%= f.date_field :start_date, required:"required", class: "contact_input" %>
              </div>
          </div>
          <div class="form-group row">
            <%= f.label :end_date, t("end_date"),
              class:"control-label col-md-3 col-sm-3 col-xs-12" %>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <%= f.date_field :end_date, required:"required", class: "contact_input" %>
              </div>
          </div>
          <div class="form-group row">
            <%= f.label :status, t("status"),
              class:"control-label col-md-3 col-sm-3 col-xs-12" %>
            <div class="col-md-6 col-sm-6 col-xs-12">
              <%= f.radio_button :status, "active" %>
              <%= f.label :active, Settings.active, class: "field-label"%>
              <br/>
              <%= f.radio_button :status, "unactive" %>
              <%= f.label :unactive, Settings.unactive, class: "field-label"%>
            </div>
          </div>
          <div class="clearfix"></div>
          <div class="ln_solid"></div>
          <div class="form-group">
            <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
              <%= link_to t("cancel"), user_subject_path(@user_subject.subject_id),
                class: "btn btn-primary" %>
              <%= link_to t("reset"), edit_user_subject_path(@user_subject),
                class: "btn btn-primary" %>
              <%= f.submit t("update"), class: "btn btn-success submit-button" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/user_subjects/show.html.erb
<div class="">
  <div class="page-title">
    <div class="title_left">
      <h3><%= t "current_course" %></h3>
    </div>
  </div>

  <div class="clearfix"></div>

  <div class="row">
    <div class="clearfix"></div>

    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_content">

          <div class="table-responsive">
            <table class="table table-striped jambo_table bulk_action">
              <thead>
                <tr class="headings">
                  <th class="column-title">
                    <%= t "name" %>
                  </th>
                  <th class="column-title">
                    <%= t "email" %>
                  </th>
                  <th class="column-title">
                    <%= t "progress" %>
                  </th>
                  <th class="column-title">
                    <%= t "status" %>
                  </th>
                  <th class="column-title">
                    <%= t "start_date" %>
                  </th>
                  <th class="column-title">
                    <%= t "end_date" %>
                  </th>
                  <th class="column-title">
                    <%= t "edit_user_subject" %>
                  </th>
                </tr>
              </thead>
              <tbody>
                <% @user_subjects.each do |user_subject| %>
                  <%= form_for user_subject, url: user_subject_path(user_subject),
                    method: :patch do |f| %>
                    <tr class="even pointer">
                      <td>
                        <%= user_subject.user.name %>
                      </td>
                      <td>
                        <%= user_subject.user.email %>
                      </td>
                      <td>
                        <%= user_subject.progress %>%
                      </td>
                      <td>
                        <%= radio_button_tag :status, "0", user_subject.active?,
                          class: "update-user-subject", data: {id: user_subject.id} %>
                        <%= label_tag :category_0, "Active", class: "field-label" %>
                        <br>
                        <%= radio_button_tag :status, "1", user_subject.unactive?,
                          class: "update-user-subject", data: {id: user_subject.id} %>
                        <%= label_tag :category_1, "Unactive" ,class: "field-label" %>
                      </td>
                      <td>
                        <%= user_subject.start_date %>
                      </td>
                      <td>
                        <%= user_subject.end_date %>
                      </td>
                      <td class="last">
                        <%= link_to t("edit_user_subject"),
                          edit_user_subject_path(user_subject.id) %>
                      </td>
                    </tr>
                  <% end %>
                <% end %>
              </tbody>
            </table>
            <%= link_to t("back"), subjects_path, class: "btn btn-success",
              data: {turbolinks: false} %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>